name: Build LaTeX document
on:
  push:
    paths:
      - '**.tex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: MoraGras_VillenaJimenez_FSD_E2E3.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: MoraGras_VillenaJimenez_FSD_E2E3.pdf